import {
  BookOpenText,
  CalendarClock,
  Compass,
  Ear,
  Eye,
  Flame,
  HandHeart,
  Heart,
  HeartHandshake,
  Hourglass,
  Leaf,
  Lightbulb,
  Lock,
  MessageCircle,
  MessagesSquare,
  Milestone,
  Mountain,
  PauseCircle,
  PenLine,
  RefreshCw,
  Route,
  Search,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  Sprout,
  Sun,
  TreeDeciduous,
  TrendingUp,
  Users,
  Wind,
  type LucideIcon,
} from "lucide-react";

/* The lucide icons course content may name. Kept deliberately small so the
   iconography stays sparing and consistent (lucide only, never emoji). */
export const COURSE_ICONS: Record<string, LucideIcon> = {
  "book-open-text": BookOpenText,
  "calendar-clock": CalendarClock,
  compass: Compass,
  ear: Ear,
  eye: Eye,
  flame: Flame,
  "hand-heart": HandHeart,
  heart: Heart,
  "heart-handshake": HeartHandshake,
  hourglass: Hourglass,
  leaf: Leaf,
  lightbulb: Lightbulb,
  lock: Lock,
  "message-circle": MessageCircle,
  "messages-square": MessagesSquare,
  milestone: Milestone,
  mountain: Mountain,
  "pause-circle": PauseCircle,
  "pen-line": PenLine,
  "refresh-cw": RefreshCw,
  route: Route,
  search: Search,
  shield: Shield,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  sparkles: Sparkles,
  sprout: Sprout,
  sun: Sun,
  "tree-deciduous": TreeDeciduous,
  "trending-up": TrendingUp,
  users: Users,
  wind: Wind,
};

export function courseIcon(name?: string): LucideIcon {
  return (name && COURSE_ICONS[name]) || Leaf;
}
